### ISSUE TITLE
Torque support

### ISSUE THREAD

**Issue by wpoely86** [itkovian/sarchive#15]
It would be really great to also have this for torque: job files and environment.

**Comment by wpoely86** [comment]
Torque puts it's job files under `/var/spool/torque/server_priv/jobs/`. It can do it in number subdirectories (0 to 9) but that's not the default.
For a job, you have two files:
- `2140198.SC`: actual job file
- `2140198JB`: xml file with environment and stuff

For an array job you also have a:
- `2140198.TA`: again xml array file
- `2140198-1.JB`, `2140198-2.JB` etc for every array index (doesn't have to start at 1).

**Comment by itkovian** [comment]
These subdirectories have fixed names? Across different Torque versions? Do you want all the array env data? I assume the difference is only the array ID?

**Comment by itkovian** [comment]
For now, see the torque branch (https://github.com/itkovian/sarchive/tree/torque). I do not have a solution ATM that I am happy with splitting between torque and slurm and trying to keep common code.

**Comment by itkovian** [comment]
The torque branch has been merged into master in commit c2fbc1e.
