### ISSUE TITLE
Allow pushing data to Elasticsearch

### ISSUE THREAD

**Issue by itkovian** [itkovian/sarchive#23]
Needed:

- A config file to describe the output choices and settings for ES
  - Should be extensible, i.e., support for other output channels baked in from the start
  - Should be in a simple format (TOML?)

- The script file can be sent as is
- The environment file should probably be parsed and sent as a JSON object with an entry per item in the file?

**Comment by wpoely86** [comment]
This definitely would be a very nice feature.

**Comment by itkovian** [comment]
#25 was merged, but has no support yet for authentication.

**Comment by itkovian** [comment]
See #42 for enhancements to this featue.
